### ISSUE TITLE
Error: failed to load program with go/packages

### ISSUE THREAD

**Issue by g4s8** [actions-contrib/golangci-lint#1]
I'm trying to integrate this action to the workflow: https://github.com/g4s8/gitstrap/blob/master/.github/workflows/go.yml

The step is:
```yaml
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: "run"
```
but it's [failing with error](https://github.com/g4s8/gitstrap/commit/014f51708f8f6d5b80c137773668ad6eab40f4f3/checks)
```
/usr/bin/docker run --name b6eba6880d708fe56640d99a39eba7f367e562_dffa87 --label b6eba6 --workdir /github/workspace --rm -e GOROOT -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/gitstrap/gitstrap":"/github/workspace" b6eba6:880d708fe56640d99a39eba7f367e562 run
level=warning msg="Failed to discover go env: failed to run 'go env': exit status 2"
level=error msg="Running error: context loading failed: failed to load program with go/packages: go [list -e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./...]: exit status 2: go: cannot find GOROOT directory: /opt/hostedtoolcache/go/1.12.9/x64\n"
##[error]Docker run failed with exit code 3
```

golangci-lint passed successfully for same repo using CircleCI builds

**Comment by jpreese** [comment]
GOROOT is being set when you call the setup-go action, and then being passed to this action:
`-e GOROOT`

The GOROOT path that the first action set, isn't a valid path inside of the Dockerfile that this action uses.

As a another note: this action just uses :latest for its backing image, which personally is a little scary to me in a CI environment.

**Comment by syntaqx** [comment]
This project was initially just a prototype to get golangci-lint functional. I will be expanding on it soon as part of new years projects, but would happily accept any improvements you have might have to help address issues. I will keep you posted as this project gets prioritized, but feel free to contribute back to help speed things up.

**Comment by g4s8** [comment]
@jpreese @syntaqx thanks, I've fixed it by using empty `GOROOT` env in action parameters:
```yaml
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      env:
        GOROOT: ""
      with:
        args: "run"
```

**Comment by wayneashleyberry** [comment]
I'm getting what looks like the same error, wondering if there's some more config that might be required in my environment?

```
Run actions-contrib/golangci-lint@master
  with:
    args: run ./...
    golangci_lint_version: v1.23
  env:
    GO111MODULE: on
    GOPRIVATE: github.com/overhq/*
    GOROOT: 
/usr/bin/docker run --name dfb4dffc47a2c204eba8f7d73305c7a8ccb_09523a --label 488dfb --workdir /github/workspace --rm -e GO111MODULE -e GOPRIVATE -e GOROOT -e INPUT_ARGS -e INPUT_GOLANGCI_LINT_VERSION -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/over-filters-api/over-filters-api":"/github/workspace" 488dfb:4dffc47a2c204eba8f7d73305c7a8ccb run ./...
level=error msg="Running error: context loading failed: failed to load program with go/packages: could not parse GOARCH and Go compiler in format \"<GOARCH> <compiler>\" from stdout of go command:\nGOROOT=/usr/local/go GOPATH=/go GO111MODULE=on PWD=/github/workspace go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]\ndir: /github/workspace\nstdout: <<>>\nstderr: <<go: github.com/overhq/httpkit@v0.0.21: reading github.com/overhq/httpkit/go.mod at revision v0.0.21: unknown revision v0.0.21\n>>"
##[error]Docker run failed with exit code 3
```

Here's my complete build setup, you can see I have two lint steps. I wanted to make sure there wasn't anything wrong with my actual code... so the first lint step installs `golangci-lint` differently and runs without any errors.

```yaml
name: go
on: [push]
env:
  GO111MODULE: on
  GOPRIVATE: github.com/overhq/*
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "1.13.8"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Config
        env:
          TOKEN: ${{ secrets.SERVICES_CI_GITHUB_ACCESS_TOKEN }}
        run: |
          git config --global url."https://services-ci:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Download
        run: go mod download

      - name: Test
        run: go test -race ./...

      - name: Build
        run: go build cmd/serve/main.go

      - name: Lint
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
          $(go env GOPATH)/bin/golangci-lint run ./...

      - name: Lint (again)
        uses: actions-contrib/golangci-lint@master
        env:
          GOROOT: ""
        with:
          args: "run ./..."
```

**Comment by trevarmand** [comment]
@wayneashleyberry did you ever find a solution to that? Struggling with this issue currently

**Comment by wayneashleyberry** [comment]
@trevarmand I don't use this action anymore, I just implemented the logic myself and it works fine.

**Comment by syntaqx** [comment]
Sorry for the delayed responses here - I don't even use this anymore, because `golangci-lint` provides their own. I will work on deprecating this accordingly. I suggest using their official one though:

```yaml
name: Test
on: [push, pull_request]
jobs:

  golangci:
    runs-on: ubuntu-latest
    name: golangci-lint
    steps:
      -
        name: Check out source
        uses: actions/checkout@v2
      -
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
```

Good luck.
