### ISSUE TITLE
support Major.Minor versions

### ISSUE THREAD

**Issue by docwhat** [actions-contrib/golangci-lint#3]
I'm not sure how to do it, but a developer should be able to lock their golangci-lint to a specific major.minor version.

**Comment by syntaqx** [comment]
Can you provide a sample use case for me to implement? Not sure if you have any preference of how to specify it from your end. This project is currently being prioritized with my new years open source work, so I will circle back when time permits. Feel free to contribute a solution if you have one.

**Comment by docwhat** [comment]
You could piggy back off of the `service.golangci-lint-version` from the [Config File](https://github.com/golangci/golangci-lint#config-file):

```yaml
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.20.x #
```
