### ISSUE TITLE
GOPATH is wrong during action execution

### ISSUE THREAD

**Issue by dvyukov** [actions-contrib/golangci-lint#9]
I've tried to use this action in my project following the instruction:
https://github.com/google/syzkaller/pull/1608/files

The run failed:
https://github.com/google/syzkaller/pull/1608/checks?check_run_id=452499065
The main reason seems to be that the project is checked out outside of GOPATH:
```
/github/workspace/pkg/cover/report.go:20:2: could not import github.com/google/syzkaller/pkg/osutil (pkg/bisect/bisect.go:15:2: cannot find package \"github.com/google/syzkaller/pkg/osutil\" in any of:\n\t/usr/local/go/src/github.com/google/syzkaller/pkg/osutil (from $GOROOT)\n\t/go/src/github.com/google/syzkaller/pkg/osutil (from $GOPATH)) 
```
I guess it's very common for any Go project. Is there an example of how to do this properly? The instructions probably need to be updated as well.

**Comment by dvyukov** [comment]
Found a way to fix the checkout problem:
```
  golangci-lint:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/syzkaller/syzkaller/go
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'go/src/github.com/google/syzkaller'
    - name: Run
      uses: actions-contrib/golangci-lint@v1
```

But the action still fails:
```
Run actions-contrib/golangci-lint@v1
/usr/bin/docker run --name dfbac039bd7b8c04c1ca2a4a6d0ea881e51_486c93 --label 488dfb --workdir /github/workspace --rm -e GOPATH -e INPUT_GOLANGCI_LINT_VERSION -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/syzkaller/syzkaller":"/github/workspace" 488dfb:ac039bd7b8c04c1ca2a4a6d0ea881e51
level=error msg="Running error: context loading failed: no go files to analyze"
level=error msg="Timeout exceeded: try increase it by passing --timeout option"
##[error]Docker run failed with exit code 4
```

Presumably it expects sources in the default location? But it can't possibly work with GOPATH...

**Comment by danielhochman** [comment]
I would try adding `working-directory`, i.e.:
```
name: Run
working-directory: go/src/github.com/google/syzkaller
uses: actions-contrib/golangci-lint@v1
```

**Comment by dvyukov** [comment]
@danielhochman Thanks!
I progressed a bit further. Syntax I used is:
```
    - name: Run
      uses: actions-contrib/golangci-lint@v1
      with:
        working-directory: go/src/github.com/google/syzkaller
```

This gave me:
```
level=error msg="Running error: context loading failed: failed to load program with go/packages: couldn't exec 'go [-json GOMOD GOPATH]': context deadline exceeded context.deadlineExceededError"
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```
https://github.com/google/syzkaller/pull/1616/checks?check_run_id=477908311

Then I tried:
```
    - name: Run
      uses: actions-contrib/golangci-lint@v1
      with:
        working-directory: go/src/github.com/google/syzkaller
        args: run ./...
```
it failed with:
```
level=error msg="Running error: context loading failed: no go files to analyze"
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```
https://github.com/google/syzkaller/pull/1616/checks?check_run_id=477912467

Somehow it does not use the .golangci.yml config?
It contains a different timeout value and lots of other settings:
https://github.com/google/syzkaller/blob/master/.golangci.yml

Then:
```
    - name: Run
      uses: actions-contrib/golangci-lint@v1
      with:
        working-directory: go/src/github.com/google/syzkaller
        args: run --timeout=10m ./...
```
produced some real warnings, timedout after 26m, not using config:
https://github.com/google/syzkaller/pull/1616/checks?check_run_id=477920864

**Comment by dvyukov** [comment]
```
    - name: Run
      uses: actions-contrib/golangci-lint@v1
      with:
        working-directory: go/src/github.com/google/syzkaller
        args: run --config=.golangci.yml ./...
```
fails with:
```
level=error msg="Can't read config: can't read viper config: open .golangci.yml: no such file or directory"
```
https://github.com/google/syzkaller/pull/1616/checks?check_run_id=477989590

**Comment by dvyukov** [comment]
Now this is finally working:
```
  golangci-lint:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/syzkaller/syzkaller/go
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'go/src/github.com/google/syzkaller'
    - name: Run
      uses: actions-contrib/golangci-lint@v1
      with:
        working-directory: go/src/github.com/google/syzkaller
        args: run --config=go/src/github.com/google/syzkaller/.golangci.yml ./...
```
